### ISSUE TITLE
Wrong sending amount is calculated

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#103]
zec-qt-wallet `17acec7`

Reproducibility: always

Steps:
Send -> Enter a recipient -> Enter 0.2 as amount -> Send

What happened:
Wrong calculation. You are about to send a zero amount transaction.

Expected result:
Correct calculation.

Notes:
This must be a recent regression because 0.5.9 doesn't have this bug.

**Comment by rex4539** [comment]
I'm assuming https://github.com/ZcashFoundation/zec-qt-wallet/commit/8bdd9e8365bfe4fd1d8d63d41a62a0c199cdebc2 broke it.

**Comment by adityapk00** [comment]
I just reverted the change. I'm a bit confused though. 

I thought in European locales, the comma "," is used as a decimal separator, and not the dot "."

Is this not true?

**Comment by rex4539** [comment]
Isn't it a safer bet to support both dot and comma? :)

**Comment by adityapk00** [comment]
The problem is that if the user has entered "12,001", should it be "12 thousand and one" or "12 point zero zero one"?

Let me see what other projects have done here.

**Comment by rex4539** [comment]
I just checked a few apps.

It appears that most apps use the comma as the only acceptable entry.

So you can only enter 12,001 and not 12.001.

If you need to send twelve thousand, you enter 12000 without comma.

I think one solution is to disable allowing a dot in that field. This way, there can never be a mistake.

**Comment by rex4539** [comment]
Hm, looks like it's a mixed bag.

Jaxx and Atomic wallet only accept a dot, while entering a comma is disabled.

I guess that works too :)

**Comment by adityapk00** [comment]
OK, I think that's the simplest. I'll only accept dots and disallow commas

**Comment by adityapk00** [comment]
In 0.5.10
