### ISSUE TITLE
Feature request. Specify blockchain data storage location

### ISSUE THREAD

**Issue by kolya182** [ZcashFoundation/zec-qt-wallet#104]
Would be nice to have this option to sync chain to external SSD instead of HDD.

**Comment by garethtdavies** [comment]
This is already implemented it's just only available to choose on initial setup. I'm actually just writing some docs for this which will be published shortly but this is the relevant section:

**Can I move the data directory?**
If you are starting zec-qt-wallet for the first time, then you can choose the advanced configuration and select the location of your data directory, which may, for example, be on a separate disk.

https://user-images.githubusercontent.com/31996805/51859084-25e60000-22eb-11e9-9433-e1236afeb0b4.png

If you have an existing data directory you would like to move it you can achieve this through the following steps with zec-qt-wallet closed:

* Create the new directory
* Copy everything in your [existing data directory](/faq/#where-is-the-default-data-directory-on-each-platform) to the new location
* Update [zcash.conf](/using-zec-qt-wallet/#customising-zcashconf) to add the line `datadir=/your/new/path` specifying the path to the newly created folder
* Restart zec-qt-wallet

This doesn't format as nicely but there is also documentation as to the default location of the datadir and zcash.conf  if you don't know where it is.

**Comment by kolya182** [comment]
This is works for me. Original reason for moving data to SSD is https://github.com/ZcashFoundation/zec-qt-wallet/issues/105

**Comment by chaserene** [comment]
@adityapk00 would you reopen this? this function doesn't exist in the app as of Zecwallet Fullnode 1.7.2. it would be important to have this choice as the blockchain grows bigger.
