### ISSUE TITLE
Sign Github releases

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zec-qt-wallet#106]
I was writing some docs as to "How to verify the download". Unless I missed something at the moment this just appears to be make sure you get it from the official GitHub repository.

So I'm wondering how this can be improved. As a start can the GitHub releases/tags be signed? I guess there could also be signatures for each of the binaries and /or checksums added - this would be required if distributing the software not via GitHub in the future.

**Comment by adityapk00** [comment]
I just implemented this! I'll make a release tomorrow with signed binaries, just doing some minor build script fixes

**Comment by garethtdavies** [comment]
Ah, awesome 😄I'll leave this open and feel free to close once those signed binaries are pushed 👍

**Comment by adityapk00** [comment]
In 0.5.10
