### ISSUE TITLE
"StartupWMClass:Code" cause mistake association of Vscode window

### ISSUE THREAD

**Issue by itarutitor** [ZcashFoundation/zec-qt-wallet#108]
Microsoft vscode have the name code.desktop in /usr/share/applications while the zec-qt-wallet have the .desktop file with a line of StartupWMClass:Code, so every time user opens vscode it will turn to be zec-qt-wallet icon and if open both, they will associate in one icon in dock.

**Comment by adityapk00** [comment]
Thanks for identifying this bug and digging into the root cause! I just changed the StartupWMClass. The fix will be in tomorrow's release
