### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by interbiznw** [ZcashFoundation/zec-qt-wallet#113]
Trying to build from source on windows, Looks like some things are missing?

To note, successfully built using same system on the 0.5.9 version but now with the recent updates it fails to build.

![2019-03-04 03_58_38-developer command prompt for vs 2017](https://user-images.githubusercontent.com/16450422/53732188-f8342f80-3e31-11e9-989b-5e5a8be2ab08.png)

**Comment by adityapk00** [comment]
It looks like your build is missing the `libsodium` library, which is a new dependency since v0.6.0

Can you regenerate your qmake build file?
```
c:\Qt5\bin\qmake.exe zec-qt-wallet.pro -spec win32-msvc CONFIG+=debug
nmake
```


More context:
The libsodium dependency that VC++ compiler needs is actually checked in into github `res/libsodium.lib`, which should hopefully just work. If it doesn't you might have to download the libsodium pre-built library from https://download.libsodium.org/libsodium/releases/

**Comment by interbiznw** [comment]
@adityapk00  

Ah yeah that was on a fresh build on a fresh pull from master, that it failed with those errors. The libsodium.lib file is in that location also. 

I Will try downloading the pre-built library

**Comment by interbiznw** [comment]
ok got rid of the res/libsodium error i think.. Now just stuck with these unresolved externals

`main.obj : error LNK2019: unresolved external symbol __imp__sodium_init referenced in function "public: int __thiscall Application::main(int,char * * const)" (?main@Application@@QAEHHQAPAD@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_hash_sha256 referenced in function "public: class QString __thiscall AppDataServer::getWormholeCode(class QString)" (?getWormholeCode@AppDataServer@@QAE?AVQString@@V2@@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_secretbox_easy referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_secretbox_open_easy referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__randombytes_buf referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_memzero referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_compare referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_increment referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_bin2hex referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_hex2bin referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
debug\zec-qt-wallet.exe : fatal error LNK1120: 10 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.`

**Comment by interbiznw** [comment]
that libsodium.lib is x64 i believe and the build is build as x86 so that libsodium gave the 
`library machine type 'x64' conflicts with the target machine type 'x86'`
Error

**Comment by adityapk00** [comment]
>thee build is build as x86 so,

I think that might be the problem. I don't think it is going to compile is x86 (32-bit) mode, since zcash uses a lot of 256-bit math and libsodium also uses 256-bit encryption. 

You will have to switch to x64 (64-bit) build

**Comment by adityapk00** [comment]
Also, if you have Visual Studio (even the community edition), can you see if the Visual Studio UI will compile it? 

After you run the `qmake` command, it should generate the `.vcproj` file, which you can open in Visual Studio, and hit compile (x64) and see if it works?

**Comment by interbiznw** [comment]
> I think that might be the problem. I don't think it is going to compile in x86 (32-bit) mode, since zcash uses a lot of 256-bit math and libsodium also uses 256-bit encryption.

but the 0.5.9 build compiles just fine like this?

Also dont think the .vcproject is output unless u change the spec

I have been using 
`C:\Qt\5.12.1\msvc2017\bin\qmake.exe zec-qt-wallet.pro -spec win32-msvc CONFIG+=debug` 
and then
`nmake`

to build the previous 0.5.9 with no issues


So to get the `.vcproj` file I am guessing I would have to:

`C:\Qt\5.12.1\msvc2017\bin\qmake.exe zec-qt-wallet.pro -tp vc CONFIG+=debug`

Did that and got this:
![image](https://user-images.githubusercontent.com/16450422/53846579-4f392200-3f62-11e9-8004-7f0087a6c37a.png)


But did get a `.vcxproj` file so i will see how that goes

**Comment by interbiznw** [comment]
fails in visual studio at the same spot

`1>Generating Code...
1>Compiling...
1>websockets.cpp
1>moc_addresscombo.cpp
1>moc_fillediconlabel.cpp
1>moc_logger.cpp
1>moc_mainwindow.cpp
1>moc_mobileappconnector.cpp
1>moc_qrcodelabel.cpp
1>moc_websockets.cpp
1>qrc_application.cpp
1>Generating Code...
1>main.obj : error LNK2019: unresolved external symbol __imp__sodium_init referenced in function "public: int __thiscall Application::main(int,char * * const)" (?main@Application@@QAEHHQAPAD@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_hash_sha256 referenced in function "public: class QString __thiscall AppDataServer::getWormholeCode(class QString)" (?getWormholeCode@AppDataServer@@QAE?AVQString@@V2@@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_secretbox_easy referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__crypto_secretbox_open_easy referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__randombytes_buf referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_memzero referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_compare referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_increment referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_bin2hex referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
1>websockets.obj : error LNK2019: unresolved external symbol __imp__sodium_hex2bin referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
1>debug\\zec-qt-wallet.exe : fatal error LNK1120: 10 unresolved externals
1>Done building project "zec-qt-wallet.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by adityapk00** [comment]
Makes sense that this is failing after 0.5.9, since the libsodium dependency was added only after 0.6.0

In any case, I’ll try tonight with a clean windows machine to see if I can reproduce it. 

The reason I’m not running into this like you are is because the official windows builds are actually cross compiled on Linux using mingw.  :)

**Comment by adityapk00** [comment]
Hmm... I just tried it on a clean machine, and the following works for me:
```
git clone git@github.com:ZcashFoundation/zec-qt-wallet.git
cd zec-qt-wallet
C:\dev\Qt\5.11.2\msvc2017_64\bin\qmake.exe .\zec-qt-wallet.pro  -spec win32-msvc   CONFIG+=debug
nmake
```

I'm surprised its not working for you. What version of MSVC are you using? Also, are you running from the `x64 native tools command prompt`? The `x86 native tools command prompt` will not work as I said earlier, since it needs 64-bit (x64)

**Comment by adityapk00** [comment]
In Visual Studio, I think you'll need to use `x64` build, and not `x86`

**Comment by adityapk00** [comment]
Ok, I finally tried with 32-bit, and I'm like 99% sure the problems you are running into are because of the 32-bit build. You need to upgrade to 64-bit. 

1. Get the 64-bit version of Qt. You're currently using 32-bit (`c:\Qt\msvc2017_64` instead of `C:\Qt\msvc2017`)
2. Run from `x64 native tools command prompt for VS 2017`

**Comment by adityapk00** [comment]
One way to still build with 32-bit is to download libsodium-1.0.16-msvc.zip from [here](https://download.libsodium.org/libsodium/releases/) , and then overwrite `res\libsodium.lib` with `libsodium-1.0.16-msvc.zip\Win32\Release\v141\static\libsodium.lib`

**Comment by interbiznw** [comment]
Ok so the x64 was already there just wasn't using it apparently so just had to add `_64` to that dir path and it got past some errors, now getting this:
![image](https://user-images.githubusercontent.com/16450422/53881229-f9976080-3fc7-11e9-990f-ce19ff910192.png)

**Comment by interbiznw** [comment]
Used `C:\Qt\5.12.1\msvc2017_64\bin\qmake.exe zec-qt-wallet.pro -spec win64-msvc CONFIG+=debug`

**Comment by interbiznw** [comment]
Hmm wiped folder and started over and got rid of the QT5Widgets error but now still getting these unresolved external symbol errors, and Yes using the x64 native tools for VS2017, and the 64bit QT

![image](https://user-images.githubusercontent.com/16450422/53882191-7e837980-3fca-11e9-9171-58591098d925.png)

**Comment by interbiznw** [comment]
Also 
![image](https://user-images.githubusercontent.com/16450422/53883462-ed160680-3fcd-11e9-856b-af65046d406c.png)

**Comment by interbiznw** [comment]
Honestly not even worried about building this on windows. What is the easiest steps to cross compile on linux for windows?

**Comment by adityapk00** [comment]
This is very mysterious. The exact same commands are working on my windows 10 box with msvc 2017/64 bit. 

Let me investigate a little.

**Comment by adityapk00** [comment]
OK, After some Googling, I still can't figure out why you're seeing the errors. We're missing something really obvious, I think.

Can you try deleting the zec-qt-wallet directory and trying everything from scratch?
```
git clone git@github.com:ZcashFoundation/zec-qt-wallet.git
cd zec-qt-wallet
C:\dev\Qt\5.11.2\msvc2017_64\bin\qmake.exe .\zec-qt-wallet.pro  -spec win32-msvc   CONFIG+=debug
nmake
```

If it still doesn't work, the only other thing I can think of is that the libsodium library is somehow corrupt. 
Can you download libsodium-1.0.16-msvc.zip from here , and then overwrite `res\libsodium.lib` with `libsodium-1.0.16-msvc.zip\Win64\Release\v141\static\libsodium.lib`

**Comment by adityapk00** [comment]
Instructions for running cross-compiled Windows on linux:
```
mkdir ~/github && cd ~/github
git clone https://github.com/mxe/mxe.git
cd mxe

make -j$(nproc) MXE_TARGETS=x86_64-w64-mingw32.static qtbase qtwebsockets libsodium

cd ~/github
git clone git@github.com:ZcashFoundation/zec-qt-wallet.git
cd zec-qt-wallet
cat zec-qt-wallet.pro | sed "s/precompile_header/release/g" | sed "s/PRECOMPILED_HEADER.*//g" > zec-qt-wallet-mingw.pro

~/github/mxe/usr/bin/x86_64-w64-mingw32.static-qmake-qt5 zec-qt-wallet-mingw.pro CONFIG+=release 
make 
```

**Comment by interbiznw** [comment]
ok had to be 

> libsodium library is somehow corrupt

Cause another new clone and build with x64 it completed

Now, how do you get it to where it doesn't have all the dll errors and they are bundled?

**Comment by adityapk00** [comment]
Ok, Good to hear. 

If you want to just run on your machine, either add the Qt5 bin directory to your PATH, or just copy over all the dlls from the Qt5 bin directory to your current directory, and it will run. 

Packaging an installer is a much more complicated process, check the wiki for instructions.

**Comment by interbiznw** [comment]
Cool thank you for all your help! Just thought maybe there was an easy to bundle them short of copying all the files to another computer since I don't have QT on the other one to just add to the PATH. I will check the wiki! Thanks again!

**Comment by adityapk00** [comment]
Great. Just so you know, you can copy over all the dll's as well to the other computer (in the same directory as `zec-qt-wallet.exe`) and it should just work.
