### ISSUE TITLE
Implement wallet.dat encryption

### ISSUE THREAD

**Issue by avirdoz** [ZcashFoundation/zec-qt-wallet#116]
Is it possible to implement wallet encryption like in bitcoin-core?

**Comment by adityapk00** [comment]
Unfortunately, the wallet.dat encryption needs to be implemented in zcashd, and is not possible to implement in zec-qt-wallet alone. 

I think they already have an open issue on the zcashd github for this. Please feel free to comment on that issue. (https://github.com/zcash/zcash/issues)

Closing this one.
