### ISSUE TITLE
[Question] Localization?

### ISSUE THREAD

**Issue by arkdlite** [ZcashFoundation/zec-qt-wallet#14]
Hello! Your GUI for Zcash is amazing, thank you for your work.
But Bitcoin-qt, Dash-qt and many others have localizations for many languages. Are you going to make possibility of translation for your project? Thanks.
I think that translation possibility could attract users from all over the world and they will use Zcash.

**Comment by adityapk00** [comment]
I'd love to localize the UIs and I could use some help :)

I've never done localization before, so how does one go about it? I understand there's some code changes required, and then we get translations done? How do we get people to contribute translations? In what format?

Do you have more info on how I can learn more to make this happen?

**Comment by arkdlite** [comment]
@adityapk00 
Sorry, I am not Qt developer. But I think this page from Qt documentation can be useful: http://doc.qt.io/qt-5/internationalization.html
I think you should see how Bitcoin-qt developers made this: https://github.com/bitcoin/bitcoin/tree/master/src/qt/locale translation docs: https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md
Some XML-like language is used by Bitcoin-qt's developers.

**Comment by adityapk00** [comment]
Ah, the links to the bitcoin translation process are helpful. Gives me a better understanding, thanks!

I'll look into this next week.

**Comment by adityapk00** [comment]
zec-qt-wallet is now localization enabled. We're working through some of the languages now. There's also instructions here of how to get started with translations: https://github.com/ZcashFoundation/zec-qt-wallet/wiki/Translations

**Comment by adityapk00** [comment]
This one took a while,but localized language support is now available in v0.5.1
