### ISSUE TITLE
Wrong behavior when stopping zcashd while zec-qt-wallet is running

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#40]
Reproducibility: always

Prerequisites:
zcashd and zec-qt-wallet are running.

Steps:
From Terminal `zcash-cli stop`

What happened:
The app "appears" to be working properly, except the following error popping up.
![screen shot 2018-11-10 at 12 17 53](https://user-images.githubusercontent.com/227442/48300284-12dd4400-e4e3-11e8-8f2d-375ed3cac6a8.png)

Expected result:
The app should clear everything and enter the same state as when you launch it without zcashd running.
![screen shot 2018-11-10 at 12 22 52](https://user-images.githubusercontent.com/227442/48300302-6fd8fa00-e4e3-11e8-8408-387d5ec28409.png)

**Comment by adityapk00** [comment]
commit 0111d0a404494ccb38658ec921d622038f849752
