### ISSUE TITLE
Inform user when a transaction is sent but internet connection is not active

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#42]
Reproducibility: always

Prerequisites:
zcashd and zec-qt-wallet are running.

Steps:
1. Kill your internet connection.
2. Send a transaction.

What happened:
The app acts like the transaction is sent normally.

Expected result:
A window appears "Your internet connection appears to be inactive. Your transaction is queued and will be sent to the Zcash network the next time your connection becomes active." or something along those lines.

Notes:
I believe the user will assume that the "Connected" info in the lower right of the main window is about the connection to the Zcash network when in fact it is about the connection to zcashd. I believe the explanation window will help clear up some of the confusion on the user's part regarding this matter. Perhaps, as an additional measure, you could add extra info to the "Connected" label when you hover the mouse over it. Right now it reads "1 ZEC = $XXX.XX". Maybe it should read "You are successfully connected to the Zcash daemon - 1 ZEC = $XXX.XX".

**Comment by adityapk00** [comment]
This is interesting one. zec-qt-wallet doesn't connect to the internet, so it has no way of knowing if the internet is connected or not. It only talks to zcashd. 

I like your suggestion of showing we are only connected to zcash daemon.

**Comment by rex4539** [comment]
How do you get the fiat price if the app doesn't connect to the internet?

**Comment by adityapk00** [comment]
I meant to say that zec-qt-wallet is not continuously connected. It gets the ZEC price at startup (and then refreshes it every hour), but can't detect if the internet is disconnected in the middle. 

Maybe zcashd has an RPC or there's an opportunity to add it? Let me look into it.

**Comment by adityapk00** [comment]
I think I found a way - I can query the number of peers via the RPC, and if that is 0, then zcashd is not connected, and I could show the appropriate warning.

**Comment by adityapk00** [comment]
Forgot to close the issue
