### ISSUE TITLE
Export Sapling HDSeed

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zec-qt-wallet#46]
Sapling uses a HD wallet and so having the HDSeed (which is available in the z_exportwallet command) is all that is required to restore these addresses. While the zec-qt-wallet currently exports all private keys a user needs to recreate this backup after any new address whereas for Sapling transactions this is no longer an issue if they had the Sapling HDSeed - they would still need to do the Sprout and transparent but they should also be able to export this HDSeed

```
HDSeed=5fa7753029b99c408e...
fingerprint=5fa7753029b99c408e...
```

https://z.cash/blog/sapling-in-hd/

**Comment by adityapk00** [comment]
Hmm... The HD seed is not available via API. It needs to be read from a file that zcashd exports (and I think  zcashd needs to be started with `-exportdir`)

This presents difficulties (what if zcashd is remote?). I wonder if I can just submit a pull request to zcashd to add an RPC for the HD key?

**Comment by garethtdavies** [comment]
Right, I thought it was available via `getwalletinfo` but that's just the fingerprint. 

In that case, I'd guess when there is support for importing a HD seed there would likely be an option to export it too so might have to wait.

**Comment by garethtdavies** [comment]
More info here so looks like this can be put on ice until it is / or is not implemented: https://chat.zcashcommunity.com/channel/zcash-dev?msg=pqdp6RrTZDY78ncDr
