### ISSUE TITLE
Able to enter negative amount after canceling Max Available

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#62]
Reproducibility: always

Steps:
1. Send -> Amount -> Check "Max Available"
2. Send -> Amount -> Uncheck "Max Available"
3. In Amount field, enter a negative amount like `-111111111111`.

What happened:
![screen shot 2018-11-23 at 22 03 33](https://user-images.githubusercontent.com/227442/48959117-0c7fab00-ef6c-11e8-84f6-42e63ff00cff.png)

Expected result:
User is not able to enter negative amount.

**Comment by rex4539** [comment]
I can reproduce on both source and release version.

After further investigation, it seems to be related either to the amount of ZEC you are holding or the number of decimals in the amount (the latter is more likely).

I can reproduce it with an address having x.xxxxxxxx ZEC but not with another one having x.xxxx ZEC.

**Comment by adityapk00** [comment]
Unfortunately, I still can't repro this with my setup despite me trying a bunch of different ways. 

I'm confident the code is right, so what's probably happening is that you're seeing a bug in Qt or Mac or somewhere between. 
So I added a special validation for this scenario, if the user happens to run into it.

**Comment by rex4539** [comment]
I'm definitely able to reproduce it 100% reliably :)

![screen shot 2019-01-08 at 23 52 17](https://user-images.githubusercontent.com/227442/50861349-053c2180-13a1-11e9-94db-9e3aff3c9ca4.png)

**Comment by adityapk00** [comment]
Can you confirm your Qt version for me? `qmake -v`?

**Comment by rex4539** [comment]
QMake version 3.1
Using Qt version 5.12.0 in /opt/local/libexec/qt5/lib
