### ISSUE TITLE
Settings view on Mac partially covered

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zec-qt-wallet#64]
This is how the settings page looks for me on Mac running v0.4.3 with the text partially hidden.

![settings_and_zec-qt-wallet_v0_4_3](https://user-images.githubusercontent.com/135382/49032858-84afc180-f162-11e8-9535-a72e5ed30033.jpg)

**Comment by garethtdavies** [comment]
So I can expand it and it looks good but should force a minimum height so it can't be covered like that,

**Comment by adityapk00** [comment]
Fixed in v0.5.0
