### ISSUE TITLE
Export transaction history

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#65]
The ability to export your transaction history is useful for tax/accounting reasons.

Can get as simple or advanced as you can invest time on it :)

Export all history or export by selecting a date range.

Option to export both transparent and shielded, just transparent or just shielded.

Export as CSV (simple) or Excel (fancy) document.

**Comment by adityapk00** [comment]
I tried added more options like filters/date range etc.., but then realized the user can do it easier in excel than in the UI in zec-qt-wallet, so I added a simple export-all functionality. 

Thanks for the idea. Available in v0.5.1
