### ISSUE TITLE
Tor connection is not working

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#80]
I am attempting to use the new feature to connect over Tor on a Windows machine. After checking the box and restarting with Tor Browser open, the wallet opens but does not connect to the network and cannot sync. I tried changing the Tor port in the config file from 9050 to 9150 and that did not solve the problem.

**Comment by adityapk00** [comment]
I'll double check on my windows machine tomorrow, but I suspect that the Tor browser download on Windows doesn't automatically install the Tor proxy for other programs to connect to it. You need to manually install the Tor proxy service from the command line. 

https://dephekt.net/blog/running-tor-as-a-windows-service-with-the-tor-browser-bundle/

**Comment by the-metalworker** [comment]
Sorry wrong button. I tried installing Tor as a service and it's still not connecting. Also when I try to turn Tor off, the wallet app crashes when I click the "settings" button in the menu.
