### ISSUE TITLE
Make "remaining balance" tooltip on Confirm Transaction window more obvious

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#82]
Per the solution to #71 the Confirm Transaction window should have a tooltip that shows what the remaining balance will be after a transaction is sent. However in the Windows wallet there is no tooltip in this window. It just shows the from address, to address, send amount, and fee.

**Comment by adityapk00** [comment]
Oh, this isn’t in any release yet. It will be in 0.5.6 which will come this week. You’ll only see it if you build from source right now.

**Comment by adityapk00** [comment]
Actually, this does seem like a bug with Qt. Thanks for reporting it. I’ll look into it.

**Comment by the-metalworker** [comment]
You're right. I wasn't letting the mouse hover long enough and wasn't sure if I was hovering in the right place, but I see it now. Could this be made more obvious with an ["info" icon](https://d379qiuk4yh6f3.cloudfront.net/imgs/common/icon--information-sky-blue.svg) that users have to hover over?

**Comment by adityapk00** [comment]
After trying this a couple of ways, I've decided not to add the extra icon on the confirm screen. My reasons are:

1. I want to keep the confirm screen ultra simple, for reasons outlined in #71 
2. The information (current balance, amount etc...) is available on the send tab, which will be the previous screen from the confirm dialog. 

Thanks for reporting this issue. If we can think of a simpler way to do this, I'm open to revisiting this issue.
