### ISSUE TITLE
Show option to enable/disable Tor before connecting to the Zcash network

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#84]
Some people might not want to show their IP address to the Zcash network ever. Right now the wallet tries connecting to the Zcash network as soon as it's opened, so users have to scramble to turn off zcashd and enable the Tor setting to hide their IP address.

This could be made simpler (and safer) by showing a popup to enable or disable Tor each time the wallet is opened, before the wallet tries connecting to the Zcash network.

```
Do you want to route traffic over Tor?
[ Yes ]  [ No ]
```

If the user selects "yes" then the wallet is automatically restarted, and from then on the pop won't show up when the wallet starts. The user can disable Tor in the settings. If they disable Tor, then the popup will show up again each time they open the wallet.

**Comment by rex4539** [comment]
This kind of UX would kind of make sense if the user is running a Tor service before the app is launched. But I think it should only be shown the first time and if the user answers "No" it shouldn't be shown again but instead perhaps show a message "You can always enable Tor in Preferences at any time".

I would definitely not want to nagged about enabling Tor every single time when I have already answered "No".

**Comment by the-metalworker** [comment]
I originally had in my proposed Tor pop-up a box that could be checked "Do not show this again." The reason I chose to leave it out is because then the user would have to re-install the wallet if they change their mind later (to reset the Tor pop-up; at least I'm guessing re-installing would make the pop-up re-appear). 

If the user can stop the wallet from connecting to the network and then change the Tor option in the settings (using the wallet in "offline mode") then that might be a good enough option and make the "Do not show this again" checkbox a reasonable addition.

**Comment by adityapk00** [comment]
Thanks for the feedback, @the-metalworker  and @rex4539. I've been thinking of this, and I think we can make it more secure by incorporating the ideas you've outlined above. 

Of course, this only works with the embedded zcashd, but I think we can show a popup the first time with the Tor option, along with other options to configure zcashd (data directory, etc...). And if the user checks the "Tor" option, then we'll add it to the zcashd.conf before we start the embedded zcashd so the user's IP is never on the network. 

I'll work the UI this week, and have something for your guys to see soon.

**Comment by adityapk00** [comment]
Forgot to close this. The Tor option is available at startup in v0.5.8
