### ISSUE TITLE
Address book import

### ISSUE THREAD

**Issue by radix42** [ZcashFoundation/zec-qt-wallet#85]
It'd be really great if the address book could import from Winzec/zcash4win/zcash4mac/other Swing wallet derivatives. Then I'd feel better about EOL'ing Winzec in the near future.

**Comment by adityapk00** [comment]
This is a good idea! I'll work on it after the holidays. 

Can you point me to the format of this file?

**Comment by garethtdavies** [comment]
I just created a sample using addresses from https://zcash.readthedocs.io/en/latest/rtd_pages/addresses.html

There is no export of address book so it's getting from `AppData\Local\ZcashSwingWalletUI\addressBook.csv`. It's a simple csv named `addressBook.csv`.

```
t1WjQ6yqv8Yh9pcc2f4JMrMpVJ3LNQXFt3u,winzec donations
t1VAggo7RusLVBzHSeYbGkxDQQhLZyigxty,ZCashSwingUI donations
zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly,Test1 
zs1z7rejlpsa98s2rrrfkwmaxu53e4ue0ulcrw0h4x5g8jl04tak0d3mm47vdtahatqrlkngh9sly,Test2
t14oHp2v54vfmdgQ3v3SNuQga8JKHTNi2a1,Test3
```

Here's the raw file (which just contains the above) but had to zip as can't upload a csv file.

[addressBook.csv.zip](https://github.com/ZcashFoundation/zec-qt-wallet/files/2700255/addressBook.csv.zip)

**Comment by adityapk00** [comment]
In v0.5.6
