### ISSUE TITLE
Update notifier

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zec-qt-wallet#87]
zec-qt-wallet should check for updates on launch and could also poll every X amount of time.

I have noticed that many users install the app once and never upgrade. Then they complain online about bugs that are already fixed in new builds.

No update mechanism required. Those can get very complicated and could involve malicious attacks.

Just a popup notification about newer build available and a link to GitHub releases repo.

**Comment by adityapk00** [comment]
I had considered this originally, but I didn't want the app to "phone home" to check for updates. I hated apps that did that. 

But I have now discovered that github has a public releases API, so I can use that! 

Anyway, implemented the version check notification.

Out of curiosity, where are you seeing people complain? I don't seem to have caught this feedback on the zcash community. Where do I monitor for this?

**Comment by adityapk00** [comment]
In v0.5.7
