### ISSUE TITLE
Not seeing recent transactions in transactions tab

### ISSUE THREAD

**Issue by acityinohio** [ZcashFoundation/zec-qt-wallet#91]
On Ubuntu 18.04, the transaction list stops at my second to last transaction. Happy to send screenshots/logs privately @adityapk00, didn't want to publicly share them.

**Comment by acityinohio** [comment]
Oh hmm, actually upon closer examination it looks like it isn't showing two Sprout shielded sends, but all other transactions are populating correctly.

**Comment by adityapk00** [comment]
Do you have the “remember sent transactions” setting enabled? Since zcashd doesn’t save sent shielded transactions, zec-qt-wallet saves it locally. 

Also, is it a sprout -> sprout transaction that is missing?

**Comment by adityapk00** [comment]
I just tried sprout -> tAddr, tAddr -> sprout and sprout -> sprout, and I couldn't reproduce the problem. Do you have more details about the transaction that might help narrow down the problem? 

Multiple destination addresses or anything special in the memo?

**Comment by acityinohio** [comment]
Sorry for the delay @adityapk00 — I took a closer look and realized that the transaction wasn't missing, it was simply hidden among the transactions in my list. Namely it was listed as a transparent send when in fact it was a transparent -> transparent + shielded Sprout send. It listed the t-addr first instead of (Shielded) which is where my confusion stemmed from. Sorry for my confusion!

**Comment by adityapk00** [comment]
Thanks for digging into this. You are right, the multiple destination addresses scenario is confusing. 

Let me see if I can make it clearer by somehow handling the multiple address case.
