### ISSUE TITLE
zec-qt-wallet shuts down remote node

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/zec-qt-wallet#92]
It's possible to get zec-qt-wallet to shut down a remote node (i.e. not the embedded zcashd) in very select circumstances that are repeatable.

I use port forwarding to connect to my remote zcashd node. I also have a custom `zcash.conf` file locally. Accidentally starting up `zec-qt-wallet` without having port forwarding running I get the following (expected due to custom zcash.conf file it is reading).

![zec-qt-wallet](https://user-images.githubusercontent.com/135382/51940019-c0b30d00-23c5-11e9-8401-ad6d6fbee1fb.jpg)

At which point I realise my error and start port forwarding. I am then greeted with the error:

![zec-qt-wallet_and_zec-qt-wallet_v0_5_8](https://user-images.githubusercontent.com/135382/51940080-e213f900-23c5-11e9-9448-471798207b2b.jpg)

At this point, nothing happens and zec-qt-wallet is blank. Then closing the application it tries to stop `zcashd` as seen by the "Waiting for zcashd to stop" message. As this is presumably running the `zcash-cli stop` command and I am now connected via port forwarding it stops my remote node.

This is obviously a bit of an edge case but I'm wondering if perhaps it can check for a running embedded `zcashd` before it issues that command (as given that other failure message it knows the embedded `zcashd` is not running)

**Comment by adityapk00** [comment]
There already is a check to see if we're running an embedded zcashd before stopping it: https://github.com/ZcashFoundation/zec-qt-wallet/blob/master/src/rpc.cpp#L1059

So, for some reason, zec-qt-wallet thinks it has started a embedded zcashd, when it has not. I think what's happening is that it tries to start it, the process starts successfully, but then zcashd exits afterwards. At this point zec-qt-wallet thinks it has started zcashd, so it tries to shut it down. 

So, there's a bug somewhere in this flow where it still thinks zcashd is running. Let me try to try to dig into the code a bit deeper.

**Comment by adityapk00** [comment]
Actually, ignore my previous comment. Two seconds after I posted it, I realized I could just check if the process was alive before sending the `stop` command. Fixed.

**Comment by adityapk00** [comment]
In 0.5.9
