### ISSUE TITLE
Memo field doesn't allow text selection (copy and paste)

### ISSUE THREAD

**Issue by geffenz** [ZcashFoundation/zec-qt-wallet#93]
This may seem unimportant, but if the memo is used for any transaction with commerce information (tracking/ship-to/invoice/etc) the information is now error prone from humans having to copy it.

For instance, a transaction that includes the user's address for communicating back to via memo (or refunding) would need to be copied by hand.

**Comment by geffenz** [comment]
This is a windows bug FYI.

**Comment by adityapk00** [comment]
Thanks for reporting this. It will be fixed in Monday's release.

**Comment by adityapk00** [comment]
In 0.5.9
