### ISSUE TITLE
Send screen should default to Z address [privacy by default]

### ISSUE THREAD

**Issue by geffenz** [ZcashFoundation/zec-qt-wallet#94]
Send screen should default to Z address [privacy by default].

Accidentally sending from a T address is easy. Windows bug.

**Comment by adityapk00** [comment]
Hmm, This should already work. It selects a Sapling address by default, and will fall back to a t-Addr if there isn't one with balance. 

Can you confirm that you have a z-addr with balance that it is not selecting by default?

**Comment by geffenz** [comment]
Confirmed it is fixed. I believe I was a release behind and can't replicate
after update.

**Comment by adityapk00** [comment]
Thanks for confirming! I'll track the related android issue on the android github. Closing this issue.
